### ISSUE TITLE
How many epochs did you train each model?

### ISSUE THREAD

**Issue by betterenvi** [xing-hu/TL-CodeSum#1]
How many epochs did you train each model mentioned in the paper?

When training the "API-Only" model, part of the log is:
```
hypotheses:18940, references: 18940
corpus_bleu: 0.0160 avg_score: 0.1902
11/14 21:36:38 valid score=0.0160 avg_score=0.1902
11/14 21:36:38 saving model to ../data_pre/model/api2nl/checkpoints
11/14 21:36:38 finished saving model
11/14 21:48:50 step 56000 epoch 6 learning rate 0.429 step-time 0.364 loss 53.745
11/14 21:49:52   valid eval: loss 56.68
11/14 21:49:52 starting decoding
hypotheses:18940, references: 18940
corpus_bleu: 0.0145 avg_score: 0.1670
11/14 21:51:54 valid score=0.0145 avg_score=0.1670
11/14 21:51:54 saving model to ../data_pre/model/api2nl/checkpoints
11/14 21:51:54 finished saving model

```

Is "avg_score" BLEU-4 score? If it is, the perf  at epoch 6 seem far from 0.2645 reported in paper.

Therefore I'd like to know how many epochs you trained each model.

**Comment by xing-hu** [comment]
The most epoch is 50 and the most step is 500000.

**Comment by betterenvi** [comment]
Which is "BLEU-4" score? corpus_bleu or avg_score?

**Comment by xing-hu** [comment]
avg_score of sentence-level BLEU

**Comment by betterenvi** [comment]
I mean, which metric is reported in the paper?

**Comment by xing-hu** [comment]
avg_score of sentence-level BLEU

**Comment by Guardian99** [comment]
How do you tokenize a source code? I am trying to augment the test dataset but i don't know how to augment the tokenize the source code? Any help would be greatly appreciated.
